quadog:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000
  
  # Effort Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: FLHipX
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: FLHipY
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: FLKnee
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: HLHipX
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint5_effort_controller:
    type: effort_controllers/JointEffortController
    joint: HLHipY
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint6_effort_controller:
    type: effort_controllers/JointEffortController
    joint: HLKnee
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint7_effort_controller:
    type: effort_controllers/JointEffortController
    joint: FRHipX
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint8_effort_controller:
    type: effort_controllers/JointEffortController
    joint: FRHipY
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint9_effort_controller:
    type: effort_controllers/JointEffortController
    joint: FRKnee
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint10_effort_controller:
    type: effort_controllers/JointEffortController
    joint: HRHipX
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint11_effort_controller:
    type: effort_controllers/JointEffortController
    joint: HRHipY
    pid: {p: 5000.0, i: 0.01, d: 100.0}

  joint12_effort_controller:
    type: effort_controllers/JointEffortController
    joint: HRKnee
    pid: {p: 5000.0, i: 0.01, d: 100.0}




